gesdinet_jwt_refresh_token:
    refresh_token_class: App\User\Entity\RefreshToken
    ttl: 2592000
    ttl_update: true
    single_use: true
    logout_firewall: api
    
    # Автоматическая установка куков
    cookie:
        enabled: true
        same_site: lax
        path: /
        domain: null
        http_only: true
        secure: false
        partitioned: false
        remove_token_from_body: true