<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260313193615 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE game_comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, game_id INT NOT NULL, author_id INT NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1B62D43E48FD905 ON game_comment (game_id)');
        $this->addSql('CREATE INDEX IDX_1B62D43F675F31B ON game_comment (author_id)');
        $this->addSql('CREATE INDEX IDX_1B62D43727ACA70 ON game_comment (parent_id)');
        $this->addSql('ALTER TABLE game_comment ADD CONSTRAINT FK_1B62D43E48FD905 FOREIGN KEY (game_id) REFERENCES game (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_comment ADD CONSTRAINT FK_1B62D43F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_comment ADD CONSTRAINT FK_1B62D43727ACA70 FOREIGN KEY (parent_id) REFERENCES game_comment (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE game_comment DROP CONSTRAINT FK_1B62D43E48FD905');
        $this->addSql('ALTER TABLE game_comment DROP CONSTRAINT FK_1B62D43F675F31B');
        $this->addSql('ALTER TABLE game_comment DROP CONSTRAINT FK_1B62D43727ACA70');
        $this->addSql('DROP TABLE game_comment');
    }
}
