<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260327193517 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE game_stage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stage_order INT NOT NULL, title VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, duration INT DEFAULT NULL, tasks JSON DEFAULT NULL, props JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, game_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F04FEAE6E48FD905 ON game_stage (game_id)');
        $this->addSql('ALTER TABLE game_stage ADD CONSTRAINT FK_F04FEAE6E48FD905 FOREIGN KEY (game_id) REFERENCES game (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stage DROP CONSTRAINT fk_c27c9369e48fd905');
        $this->addSql('DROP TABLE message_type');
        $this->addSql('DROP TABLE stage');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE message_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE stage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stage_order INT NOT NULL, title VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, duration INT DEFAULT NULL, tasks JSON DEFAULT NULL, props JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, game_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_c27c9369e48fd905 ON stage (game_id)');
        $this->addSql('ALTER TABLE stage ADD CONSTRAINT fk_c27c9369e48fd905 FOREIGN KEY (game_id) REFERENCES game (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_stage DROP CONSTRAINT FK_F04FEAE6E48FD905');
        $this->addSql('DROP TABLE game_stage');
    }
}
