<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260524175627 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE game_judge_log_id_seq CASCADE');
        $this->addSql('ALTER INDEX idx_1b62d43e48fd905 RENAME TO IDX_F4DA690CE48FD905');
        $this->addSql('ALTER INDEX idx_1b62d43727aca70 RENAME TO IDX_F4DA690C727ACA70');
        $this->addSql('ALTER INDEX idx_1b62d43f675f31b RENAME TO IDX_F4DA690CF675F31B');
        $this->addSql('ALTER TABLE game_judge_logs ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE game_judge_logs ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN game_judge_logs.created_at IS \'\'');
        $this->addSql('ALTER INDEX uniq_game_judge_log_game RENAME TO UNIQ_58A6BE21E48FD905');
        $this->addSql('ALTER INDEX idx_47762c9fe48fd905 RENAME TO IDX_7BF937F2E48FD905');
        $this->addSql('ALTER INDEX idx_47762c9ff675f31b RENAME TO IDX_7BF937F2F675F31B');
        $this->addSql('ALTER INDEX idx_f04feae6e48fd905 RENAME TO IDX_5297C7ACE48FD905');
        $this->addSql('ALTER INDEX idx_232b318cf675f31b RENAME TO IDX_FF232B31F675F31B');
        $this->addSql('ALTER INDEX idx_ba71692d700047d2 RENAME TO IDX_5E6BE217700047D2');
        $this->addSql('ALTER INDEX idx_ba71692df675f31b RENAME TO IDX_5E6BE217F675F31B');
        $this->addSql('ALTER INDEX idx_97a0ada3f4bd7827 RENAME TO IDX_54469DF4F4BD7827');
        $this->addSql('ALTER INDEX idx_97a0ada3f675f31b RENAME TO IDX_54469DF4F675F31B');
        $this->addSql('ALTER INDEX uniq_9bace7e1c74f2195 RENAME TO UNIQ_F02938B8C74F2195');
        $this->addSql('ALTER TABLE users DROP is_active');
        $this->addSql('ALTER TABLE users DROP is_blocked');
        $this->addSql('ALTER TABLE users DROP is_verified');
        $this->addSql('ALTER INDEX uniq_8d93d649e7927c74 RENAME TO UNIQ_1483A5E9E7927C74');
        $this->addSql('ALTER INDEX uniq_8d93d649aa08cb10 RENAME TO UNIQ_1483A5E9AA08CB10');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE game_judge_log_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('ALTER INDEX idx_f4da690c727aca70 RENAME TO idx_1b62d43727aca70');
        $this->addSql('ALTER INDEX idx_f4da690cf675f31b RENAME TO idx_1b62d43f675f31b');
        $this->addSql('ALTER INDEX idx_f4da690ce48fd905 RENAME TO idx_1b62d43e48fd905');
        $this->addSql('ALTER TABLE game_judge_logs ALTER id SET DEFAULT nextval(\'game_judge_log_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE game_judge_logs ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN game_judge_logs.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX uniq_58a6be21e48fd905 RENAME TO uniq_game_judge_log_game');
        $this->addSql('ALTER INDEX idx_7bf937f2e48fd905 RENAME TO idx_47762c9fe48fd905');
        $this->addSql('ALTER INDEX idx_7bf937f2f675f31b RENAME TO idx_47762c9ff675f31b');
        $this->addSql('ALTER INDEX idx_5297c7ace48fd905 RENAME TO idx_f04feae6e48fd905');
        $this->addSql('ALTER INDEX idx_ff232b31f675f31b RENAME TO idx_232b318cf675f31b');
        $this->addSql('ALTER INDEX idx_5e6be217700047d2 RENAME TO idx_ba71692d700047d2');
        $this->addSql('ALTER INDEX idx_5e6be217f675f31b RENAME TO idx_ba71692df675f31b');
        $this->addSql('ALTER INDEX idx_54469df4f675f31b RENAME TO idx_97a0ada3f675f31b');
        $this->addSql('ALTER INDEX idx_54469df4f4bd7827 RENAME TO idx_97a0ada3f4bd7827');
        $this->addSql('ALTER INDEX uniq_f02938b8c74f2195 RENAME TO uniq_9bace7e1c74f2195');
        $this->addSql('ALTER TABLE "users" ADD is_active BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE "users" ADD is_blocked BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE "users" ADD is_verified BOOLEAN NOT NULL');
        $this->addSql('ALTER INDEX uniq_1483a5e9e7927c74 RENAME TO uniq_8d93d649e7927c74');
        $this->addSql('ALTER INDEX uniq_1483a5e9aa08cb10 RENAME TO uniq_8d93d649aa08cb10');
    }
}
