<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260321145840 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE favorite_game DROP CONSTRAINT fk_cd2d28b3e48fd905');
        $this->addSql('ALTER TABLE favorite_game DROP CONSTRAINT fk_cd2d28b37e3c61f9');
        $this->addSql('DROP TABLE favorite_game');
        $this->addSql('ALTER TABLE game_like DROP updated_at');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE favorite_game (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, game_id INT NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_cd2d28b37e3c61f9 ON favorite_game (owner_id)');
        $this->addSql('CREATE INDEX idx_cd2d28b3e48fd905 ON favorite_game (game_id)');
        $this->addSql('ALTER TABLE favorite_game ADD CONSTRAINT fk_cd2d28b3e48fd905 FOREIGN KEY (game_id) REFERENCES game (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE favorite_game ADD CONSTRAINT fk_cd2d28b37e3c61f9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_like ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    }
}
